[package]
authors = ["kizkoh <mac-daisuki@live.jp>"]
name = "dupharvest"
version = "0.1.0"

[dependencies]
chrono = "0.4.0"
lazy_static = "0.2.8"

[dependencies.pnet]
features = [""]
version = "0.19.0"
